version: '3.7'
services:
  template:
    build:
        context: microservices/template
    ports:
        - 8080:8080
    command:
        -grpc-port=9090
        -http-port=8080
        -db-host=mongodb://172.20.0.2:27017
        -log-level=-1
        -log-time-format=2006-01-02T15:04:05.999999999Z07:00
  mongodb:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - mongodb:/data/db
volumes:
    mongodb:
